authtest.c File Reference
Test program for authentication functions.
#include <stdio.h>
#include <config.h>
#include <auth.h>
#include <sw.h>
#include <fs.h>
#include <hal.h>
#include <transaction.h>
#include <netinet/in.h>
Functions
int main (int argc, char *argv[])
Variables
iu8 authstate
Variable indicating current authentication state.
iu32 challenge [2]
Value of the last with Get Challenge fetched random challenge.
iu8 challvalidity
Validity of challenge.
Detailed Description
Test program for authentication functions.
Id:
authtest.c,v 1.11 2002/12/22 15:42:55 m Exp
Function Documentation
int main (int argc, char * argv[])
References auth_createVerifyCryptogram(), auth_init(), auth_setPin(), auth_verifyPin(), authstate, challenge, challvalidity, FALSE, fs_init(), hal_eeprom_read(), hal_init(), hal_rnd_getBlock(), PIN_TYPE_EXT, PIN_TYPE_PIN, PIN_TYPE_PUK, sw, and ta_commit().
Variable Documentation
iu8 authstate
Variable indicating current authentication state.
Single bit flags indicate, which authorization process has been successful. The flag is cleared, at the reset of the card and after unsuccessful authorization processes.
Valid flags are:
AUTH_FLAG_PIN
AUTH_FLAG_KEY
iu32 challenge[2]
Value of the last with Get Challenge fetched random challenge.
Referenced by auth_createVerifyCryptogram(), auth_getChallenge(), and main().
iu8 challvalidity
Validity of challenge.
The initial value if challvalidity is 2. This is decremented at the start of the command loop, so that it is 1 at the command following a Get Challenge.
Referenced by auth_createVerifyCryptogram(), auth_getChallenge(), auth_init(), and main().