commands.c File Reference
Commands.
#include <auth.h>
#include <hal.h>
#include <commands.h>
#include <config.h>
#include <crypt.h>
#include <fs.h>
#include <log.h>
#include <stddef.h>
#include <string.h>
#include <sw.h>
#include <t0.h>
#include <tools.h>
#include <types.h>
Defines
#define pinssize (PIN_LEN+PIN_LEN)
#define pin1len PIN_LEN
Functions
void cmd_write (void)
Write EEPROM. (Test command).
void cmd_read (void)
Read EEPROM. (Test command).
void cmd_changeUnblockPIN (void)
Change or Unblock PIN.
void cmd_create (void)
Create File.
void cmd_delete (void)
Delete File.
void cmd_extAuth (void)
External Authentication.
void cmd_getChallenge (void)
Get Challenge.
void cmd_getResponse (void)
Get Response.
void cmd_intAuth (void)
Internal Authentication.
void cmd_readBinary (void)
Read Binary.
void cmd_select (void)
Select File.
void cmd_updateBinary (void)
Update Binary.
void cmd_verifyKeyPIN (void)
Verify Key/Verify PIN.
Variables
iu8 resplen
Valid data in response array. Invalid if zero.
iu8 response [8]
Data returned by Get Response command.
Detailed Description
Commands. The documentation of the commands is on the main page of the doxygen documentation.
Id:
commands.c,v 1.27 2003/03/30 12:42:21 m Exp
Define Documentation
#define pin1len PIN_LEN
#define pinssize (PIN_LEN+PIN_LEN)
Function Documentation
void cmd_changeUnblockPIN (void)
Change or Unblock PIN.
References auth_setPin(), auth_verifyPin(), INS_UNBLOCK_PIN, max, PIN_LEN, PIN_TYPE_PIN, PUK_LEN, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_create (void)
Create File.
References s_finfo::ac, auth_checkAc(), fs_create(), fs_getData(), FS_TYPE_DF, hton_us(), selected, SW_NOT_ALLOWED, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), t0_testP3(), and s_finfo::type.
Referenced by main().
void cmd_delete (void)
Delete File.
References s_finfo::ac, auth_checkAc(), fs_delete(), fs_getData(), FS_TYPE_DF, hal_io_recByteT0(), selected, SW_NOT_ALLOWED, SW_OK, sw_set(), t0_sendAck(), t0_testP1P2(), t0_testP3(), and s_finfo::type.
Referenced by main().
void cmd_extAuth (void)
External Authentication.
References auth_createVerifyCryptogram(), CRYPT_BLOCK_LEN, FALSE, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_getChallenge (void)
Get Challenge.
References auth_getChallenge(), CRYPT_BLOCK_LEN, hal_io_sendByteT0(), SW_OK, sw_set(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_getResponse (void)
Get Response.
References hal_io_sendByteT0(), resplen, response, SW_OK, sw_set(), SW_WRONG_CONDITION, SW_WRONG_LE, t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_intAuth (void)
Internal Authentication.
References auth_createVerifyCryptogram(), CRYPT_BLOCK_LEN, resplen, response, SW_AVAILABLE, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), t0_testP3(), and TRUE.
Referenced by main().
void cmd_read (void)
Read EEPROM. (Test command).
References hal_eeprom_read(), hal_io_sendByteT0(), header, max, SW_OK, sw_set(), and t0_sendAck().
Referenced by main().
void cmd_readBinary (void)
Read Binary.
References s_finfo::ac, auth_checkAc(), fs_getData(), FS_TYPE_EF, fstream_read(), fstream_test(), hal_io_sendByteT0(), max, s_fstream::pos, selected, s_fstream::size, SW_NOT_ALLOWED, SW_OK, sw_set(), SW_WRONG_REFERENCE, t0_sendAck(), and s_finfo::type.
Referenced by main().
void cmd_select (void)
Select File.
References s_finfo::fid, fs_getFPath(), hal_io_recByteT0(), hton_us(), resplen, response, selected, s_finfo::size, SW_AVAILABLE, sw_set(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_updateBinary (void)
Update Binary.
References s_finfo::ac, auth_checkAc(), fs_getData(), FS_TYPE_EF, fstream_test(), fstream_write(), hal_io_recByteT0(), s_fstream::pos, selected, s_fstream::size, SW_NOT_ALLOWED, SW_OK, sw_set(), SW_WRONG_LEN, SW_WRONG_REFERENCE, t0_sendCAck(), t0_testP3(), and s_finfo::type.
Referenced by main().
void cmd_verifyKeyPIN (void)
Verify Key/Verify PIN.
This function is a combined implementation of Verify Key and Verify PIN. This is done to save code size.
References ADM_KEY_LEN, auth_verifyPin(), INS_VERIFY_KEY, PIN_LEN, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_write (void)
Write EEPROM. (Test command).
References hal_eeprom_write(), hal_io_recByteT0(), header, SW_OK, sw_set(), SW_WRONG_LEN, t0_sendCAck(), and t0_testP3().
Referenced by main().
Variable Documentation
iu8 resplen
Valid data in response array. Invalid if zero.
Referenced by cmd_getResponse(), cmd_intAuth(), cmd_select(), and main().
iu8 response[8]
Data returned by Get Response command.
The size of this array is the max. of sizeof(S_FINFO) and CRYPT_BLOCK_LEN.
Referenced by cmd_getResponse(), cmd_intAuth(), and cmd_select().