commands.h File Reference
Command declarations.
Defines
#define CLA_PROP 0x80
CLA byte: Proprietary.
#define INS_WRITE 0x02
INS byte: Write EEPROM.
#define INS_READ 0x04
INS byte: Read EEPROM.
#define INS_LED 0x06
INS byte: LED Effects.
#define INS_CHANGE_PIN 0x24
INS byte: Change PIN.
#define INS_CREATE 0xE0
INS byte: Create File.
#define INS_DELETE 0xE4
INS byte: Delete File.
#define INS_EXTERNAL_AUTH 0x82
INS byte: External Authentication.
#define INS_GET_CHALLENGE 0x84
INS byte: Get Challenge.
#define INS_GET_RESPONSE 0xC0
INS byte: Get Response.
#define INS_INTERNAL_AUTH 0x88
INS byte: Internal Authentication.
#define INS_READ_BINARY 0xB0
INS byte: Read Binary.
#define INS_SELECT 0xA4
INS byte: Select File.
#define INS_UNBLOCK_PIN 0x2C
INS byte: Unblock PIN.
#define INS_UPDATE_BINARY 0xD6
INS byte: Update Binary.
#define INS_VERIFY_KEY 0x2A
INS byte: Verify Key.
#define INS_VERIFY_PIN 0x20
INS byte: Verify PIN.
Functions
void cmd_write (void)
Write EEPROM. (Test command).
void cmd_read (void)
Read EEPROM. (Test command).
void cmd_led (void)
LED Effects.
void cmd_changeUnblockPIN (void)
Change or Unblock PIN.
void cmd_create (void)
Create File.
void cmd_delete (void)
Delete File.
void cmd_extAuth (void)
External Authentication.
void cmd_getChallenge (void)
Get Challenge.
void cmd_getResponse (void)
Get Response.
void cmd_intAuth (void)
Internal Authentication.
void cmd_readBinary (void)
Read Binary.
void cmd_select (void)
Select File.
void cmd_updateBinary (void)
Update Binary.
void cmd_verifyKeyPIN (void)
Verify Key/Verify PIN.
Variables
iu8 resplen
Valid data in response array. Invalid if zero.
Detailed Description
Command declarations. The documentation of the commands is on the main page of the doxygen documentation.
Id:
commands.h,v 1.15 2002/12/22 15:42:55 m Exp
Define Documentation
#define CLA_PROP 0x80
CLA byte: Proprietary.
Referenced by main().
#define INS_CHANGE_PIN 0x24
INS byte: Change PIN.
Referenced by main().
#define INS_CREATE 0xE0
INS byte: Create File.
Referenced by main().
#define INS_DELETE 0xE4
INS byte: Delete File.
Referenced by main().
#define INS_EXTERNAL_AUTH 0x82
INS byte: External Authentication.
Referenced by main().
#define INS_GET_CHALLENGE 0x84
INS byte: Get Challenge.
Referenced by main().
#define INS_GET_RESPONSE 0xC0
INS byte: Get Response.
Referenced by main().
#define INS_INTERNAL_AUTH 0x88
INS byte: Internal Authentication.
Referenced by main().
#define INS_LED 0x06
INS byte: LED Effects.
Referenced by main().
#define INS_READ 0x04
INS byte: Read EEPROM.
Referenced by main().
#define INS_READ_BINARY 0xB0
INS byte: Read Binary.
Referenced by main().
#define INS_SELECT 0xA4
INS byte: Select File.
Referenced by main().
#define INS_UNBLOCK_PIN 0x2C
INS byte: Unblock PIN.
Referenced by cmd_changeUnblockPIN(), and main().
#define INS_UPDATE_BINARY 0xD6
INS byte: Update Binary.
Referenced by main().
#define INS_VERIFY_KEY 0x2A
INS byte: Verify Key.
Referenced by cmd_verifyKeyPIN(), and main().
#define INS_VERIFY_PIN 0x20
INS byte: Verify PIN.
Referenced by main().
#define INS_WRITE 0x02
INS byte: Write EEPROM.
Referenced by main().
Function Documentation
void cmd_changeUnblockPIN (void)
Change or Unblock PIN.
References auth_setPin(), auth_verifyPin(), INS_UNBLOCK_PIN, max, PIN_LEN, PIN_TYPE_PIN, PUK_LEN, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_create (void)
Create File.
References s_finfo::ac, auth_checkAc(), fs_create(), fs_getData(), FS_TYPE_DF, hton_us(), selected, SW_NOT_ALLOWED, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), t0_testP3(), and s_finfo::type.
Referenced by main().
void cmd_delete (void)
Delete File.
References s_finfo::ac, auth_checkAc(), fs_delete(), fs_getData(), FS_TYPE_DF, hal_io_recByteT0(), selected, SW_NOT_ALLOWED, SW_OK, sw_set(), t0_sendAck(), t0_testP1P2(), t0_testP3(), and s_finfo::type.
Referenced by main().
void cmd_extAuth (void)
External Authentication.
References auth_createVerifyCryptogram(), CRYPT_BLOCK_LEN, FALSE, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_getChallenge (void)
Get Challenge.
References auth_getChallenge(), CRYPT_BLOCK_LEN, hal_io_sendByteT0(), SW_OK, sw_set(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_getResponse (void)
Get Response.
References hal_io_sendByteT0(), resplen, response, SW_OK, sw_set(), SW_WRONG_CONDITION, SW_WRONG_LE, t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_intAuth (void)
Internal Authentication.
References auth_createVerifyCryptogram(), CRYPT_BLOCK_LEN, resplen, response, SW_AVAILABLE, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), t0_testP3(), and TRUE.
Referenced by main().
void cmd_led (void)
LED Effects.
Referenced by main().
void cmd_read (void)
Read EEPROM. (Test command).
References hal_eeprom_read(), hal_io_sendByteT0(), header, max, SW_OK, sw_set(), and t0_sendAck().
Referenced by main().
void cmd_readBinary (void)
Read Binary.
References s_finfo::ac, auth_checkAc(), fs_getData(), FS_TYPE_EF, fstream_read(), fstream_test(), hal_io_sendByteT0(), max, s_fstream::pos, selected, s_fstream::size, SW_NOT_ALLOWED, SW_OK, sw_set(), SW_WRONG_REFERENCE, t0_sendAck(), and s_finfo::type.
Referenced by main().
void cmd_select (void)
Select File.
References s_finfo::fid, fs_getFPath(), hal_io_recByteT0(), hton_us(), resplen, response, selected, s_finfo::size, SW_AVAILABLE, sw_set(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_updateBinary (void)
Update Binary.
References s_finfo::ac, auth_checkAc(), fs_getData(), FS_TYPE_EF, fstream_test(), fstream_write(), hal_io_recByteT0(), s_fstream::pos, selected, s_fstream::size, SW_NOT_ALLOWED, SW_OK, sw_set(), SW_WRONG_LEN, SW_WRONG_REFERENCE, t0_sendCAck(), t0_testP3(), and s_finfo::type.
Referenced by main().
void cmd_verifyKeyPIN (void)
Verify Key/Verify PIN.
This function is a combined implementation of Verify Key and Verify PIN. This is done to save code size.
References ADM_KEY_LEN, auth_verifyPin(), INS_VERIFY_KEY, PIN_LEN, SW_OK, sw_set(), t0_recBlock(), t0_sendAck(), t0_testP1P2(), and t0_testP3().
Referenced by main().
void cmd_write (void)
Write EEPROM. (Test command).
References hal_eeprom_write(), hal_io_recByteT0(), header, SW_OK, sw_set(), SW_WRONG_LEN, t0_sendCAck(), and t0_testP3().
Referenced by main().
Variable Documentation
iu8 resplen
Valid data in response array. Invalid if zero.
Referenced by cmd_getResponse(), cmd_intAuth(), cmd_select(), and main().