ctapi.h File Reference
Declarations for virtual CT-API library.
#include <types.h>
Defines
#define CTAPI_AD_ICC1 0
#define CTAPI_AD_CT 1
#define CTAPI_AD_HOST 2
#define CTAPI_RV_OK 0
#define CTAPI_RV_ERR_INVALID -1
#define CTAPI_RV_ERR_CT -8
#define CTAPI_RV_ERR_TRANS -10
#define CTAPI_RV_ERR_MEMORY -11
#define CTAPI_RV_ERR_HOST -127
#define CTAPI_RV_ERR_HTSI -128
#define CTAPI_PORT 1
#define CTAPI_CLA 0x20
#define CTAPI_INS_RESET_CT 0x11
#define CTAPI_INS_REQUEST_ICC 0x12
#define CTAPI_INS_GET_STATUS 0x13
#define CTAPI_INS_EJECT_ICC 0x14
#define CTAPI_INS_EEPROM 0xE0
Typedefs
typedef unsigned char IU8
typedef signed char IS8
typedef unsigned short IU16
typedef signed short IS16
typedef unsigned long IU32
typedef signed long IS32
Functions
IS8 CT_forkIcc (void)
IS8 CT_stopIcc (void)
IS8 CT_ifdCmdEepromFile (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
Parses EEPROM FILE command.
IS8 CT_ifdCmdResetCT (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdRequestICC (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdGetStatus (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdEjectICC (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmd (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_iccCmd (IU8 *dad, IU8 *sad, IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_init (IU16 ctn, IU16 pn)
IS8 CT_data (IU16 ctn, IU8 *dad, IU8 *sad, IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_close (IU16 ctn)
Variables
int fd_fromCard [2]
int fd_toCard [2]
int loadEepromFile
int saveEepromFile
char eepromFile [256]
int fdEepromFile
Detailed Description
Declarations for virtual CT-API library.
Id:
ctapi.h,v 1.2 2002/12/22 23:16:15 m Exp
Define Documentation
#define CTAPI_AD_CT 1
Referenced by CT_data().
#define CTAPI_AD_HOST 2
Referenced by CT_data().
#define CTAPI_AD_ICC1 0
Referenced by CT_data().
#define CTAPI_CLA 0x20
#define CTAPI_INS_EEPROM 0xE0
Referenced by CT_ifdCmd().
#define CTAPI_INS_EJECT_ICC 0x14
Referenced by CT_ifdCmd().
#define CTAPI_INS_GET_STATUS 0x13
Referenced by CT_ifdCmd().
#define CTAPI_INS_REQUEST_ICC 0x12
Referenced by CT_ifdCmd().
#define CTAPI_INS_RESET_CT 0x11
Referenced by CT_ifdCmd().
#define CTAPI_PORT 1
Referenced by CT_init().
#define CTAPI_RV_ERR_CT -8
#define CTAPI_RV_ERR_HOST -127
#define CTAPI_RV_ERR_HTSI -128
#define CTAPI_RV_ERR_INVALID -1
#define CTAPI_RV_ERR_MEMORY -11
#define CTAPI_RV_ERR_TRANS -10
Referenced by CT_t0().
#define CTAPI_RV_OK 0
Referenced by CT_close(), CT_forkIcc(), CT_ifdCmdRequestICC(), CT_ifdCmdResetCT(), and CT_t0().
Typedef Documentation
typedef signed short IS16
typedef signed long IS32
typedef signed char IS8
typedef unsigned short IU16
typedef unsigned long IU32
typedef unsigned char IU8
Function Documentation
IS8 CT_close (IU16 ctn)
References CT_stopIcc(), CTAPI_RV_OK, and cthandle.
IS8 CT_data (IU16 ctn, IU8 * dad, IU8 * sad, IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_iccCmd(), CT_ifdCmd(), CTAPI_AD_CT, CTAPI_AD_HOST, CTAPI_AD_ICC1, and cthandle.
IS8 CT_forkIcc (void)
References atr, atrlen, CT_stopIcc(), CTAPI_RV_OK, fd_fromCard, fd_toCard, and pidVirtuaCard.
Referenced by CT_ifdCmdRequestICC(), and CT_ifdCmdResetCT().
IS8 CT_iccCmd (IU8 * dad, IU8 * sad, IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_t0(), and pidVirtuaCard.
Referenced by CT_data().
IS8 CT_ifdCmd (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_ifdCmdEepromFile(), CT_ifdCmdEjectICC(), CT_ifdCmdGetStatus(), CT_ifdCmdRequestICC(), CT_ifdCmdResetCT(), CTAPI_INS_EEPROM, CTAPI_INS_EJECT_ICC, CTAPI_INS_GET_STATUS, CTAPI_INS_REQUEST_ICC, and CTAPI_INS_RESET_CT.
Referenced by CT_data().
IS8 CT_ifdCmdEepromFile (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
Parses EEPROM FILE command.
CLA: '20'
INS: 'E0'
P1:
bit 1: Save EEPROM to file at eject or reset.
bit 2: Load EEPROM from file at reset.
P2: RFU
Lc: Length of file name
Data: File name (possibly including path) without null-termination
References eepromFile, loadEepromFile, and saveEepromFile.
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdEjectICC (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_stopIcc().
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdGetStatus (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References pidVirtuaCard.
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdRequestICC (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References atr, atrlen, CT_forkIcc(), and CTAPI_RV_OK.
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdResetCT (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References atr, atrlen, CT_forkIcc(), CT_stopIcc(), and CTAPI_RV_OK.
Referenced by CT_ifdCmd().
IS8 CT_init (IU16 ctn, IU16 pn)
References CTAPI_PORT, cthandle, and pidVirtuaCard.
IS8 CT_stopIcc (void)
References fd_toCard, and pidVirtuaCard.
Referenced by CT_close(), CT_forkIcc(), CT_ifdCmdEjectICC(), and CT_ifdCmdResetCT().
Variable Documentation
char eepromFile[256]
Referenced by CT_ifdCmdEepromFile(), hal_init(), and hal_io_recByteT0().
int fd_fromCard[2]
Referenced by CT_forkIcc(), CT_t0(), hal_init(), hal_io_recByteT0(), and hal_io_sendByteT0().
int fd_toCard[2]
Referenced by CT_forkIcc(), CT_stopIcc(), CT_t0(), and hal_io_recByteT0().
int fdEepromFile
Referenced by hal_init(), and hal_io_recByteT0().
int loadEepromFile
Referenced by CT_ifdCmdEepromFile(), and hal_init().
int saveEepromFile
Referenced by CT_ifdCmdEepromFile(), and hal_io_recByteT0().