ctapi.c File Reference
Virtual CT-API library.
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <ctapi.h>
#include <main.h>
#include <types.h>
#include <sw.h>
Functions
IS8 CT_forkIcc (void)
IS8 CT_stopIcc (void)
IS8 CT_ifdCmdResetCT (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdRequestICC (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdGetStatus (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdEjectICC (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_ifdCmdEepromFile (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
Parses EEPROM FILE command.
IS8 CT_ifdCmd (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
int CT_t0 (IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_iccCmd (IU8 *dad, IU8 *sad, IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_init (IU16 ctn, IU16 pn)
IS8 CT_data (IU16 ctn, IU8 *dad, IU8 *sad, IU16 lenc, IU8 *command, IU16 *lenr, IU8 *response)
IS8 CT_close (IU16 ctn)
Variables
IS32 cthandle = -1
int fd_fromCard [2]
int fd_toCard [2]
pid_t pidVirtuaCard = 0
int loadEepromFile = FALSE
int saveEepromFile = FALSE
char eepromFile [256]
int fdEepromFile
char atr [32]
int atrlen = 0
Detailed Description
Virtual CT-API library.
Id:
ctapi.c,v 1.4 2002/12/24 13:29:57 m Exp
Function Documentation
IS8 CT_close (IU16 ctn)
References CT_stopIcc(), CTAPI_RV_OK, and cthandle.
IS8 CT_data (IU16 ctn, IU8 * dad, IU8 * sad, IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_iccCmd(), CT_ifdCmd(), CTAPI_AD_CT, CTAPI_AD_HOST, CTAPI_AD_ICC1, and cthandle.
IS8 CT_forkIcc (void)
References atr, atrlen, CT_stopIcc(), CTAPI_RV_OK, fd_fromCard, fd_toCard, and pidVirtuaCard.
Referenced by CT_ifdCmdRequestICC(), and CT_ifdCmdResetCT().
IS8 CT_iccCmd (IU8 * dad, IU8 * sad, IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_t0(), and pidVirtuaCard.
Referenced by CT_data().
IS8 CT_ifdCmd (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_ifdCmdEepromFile(), CT_ifdCmdEjectICC(), CT_ifdCmdGetStatus(), CT_ifdCmdRequestICC(), CT_ifdCmdResetCT(), CTAPI_INS_EEPROM, CTAPI_INS_EJECT_ICC, CTAPI_INS_GET_STATUS, CTAPI_INS_REQUEST_ICC, and CTAPI_INS_RESET_CT.
Referenced by CT_data().
IS8 CT_ifdCmdEepromFile (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
Parses EEPROM FILE command.
CLA: '20'
INS: 'E0'
P1:
bit 1: Save EEPROM to file at eject or reset.
bit 2: Load EEPROM from file at reset.
P2: RFU
Lc: Length of file name
Data: File name (possibly including path) without null-termination
References eepromFile, loadEepromFile, and saveEepromFile.
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdEjectICC (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CT_stopIcc().
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdGetStatus (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References pidVirtuaCard.
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdRequestICC (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References atr, atrlen, CT_forkIcc(), and CTAPI_RV_OK.
Referenced by CT_ifdCmd().
IS8 CT_ifdCmdResetCT (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References atr, atrlen, CT_forkIcc(), CT_stopIcc(), and CTAPI_RV_OK.
Referenced by CT_ifdCmd().
IS8 CT_init (IU16 ctn, IU16 pn)
References CTAPI_PORT, cthandle, and pidVirtuaCard.
IS8 CT_stopIcc (void)
References fd_toCard, and pidVirtuaCard.
Referenced by CT_close(), CT_forkIcc(), CT_ifdCmdEjectICC(), and CT_ifdCmdResetCT().
int CT_t0 (IU16 lenc, IU8 * command, IU16 * lenr, IU8 * response)
References CTAPI_RV_ERR_TRANS, CTAPI_RV_OK, fd_fromCard, fd_toCard, and TRUE.
Referenced by CT_iccCmd().
Variable Documentation
char atr[32]
Referenced by CT_forkIcc(), CT_ifdCmdRequestICC(), and CT_ifdCmdResetCT().
int atrlen = 0
Referenced by CT_forkIcc(), CT_ifdCmdRequestICC(), and CT_ifdCmdResetCT().
IS32 cthandle = -1
Referenced by CT_close(), CT_data(), and CT_init().
char eepromFile[256]
Referenced by CT_ifdCmdEepromFile(), hal_init(), and hal_io_recByteT0().
int fd_fromCard[2]
Referenced by CT_forkIcc(), CT_t0(), hal_init(), hal_io_recByteT0(), and hal_io_sendByteT0().
int fd_toCard[2]
Referenced by CT_forkIcc(), CT_stopIcc(), CT_t0(), and hal_io_recByteT0().
int fdEepromFile
Referenced by hal_init(), and hal_io_recByteT0().
int loadEepromFile = FALSE
Referenced by CT_ifdCmdEepromFile(), and hal_init().
pid_t pidVirtuaCard = 0
Referenced by CT_forkIcc(), CT_iccCmd(), CT_ifdCmdGetStatus(), CT_init(), and CT_stopIcc().
int saveEepromFile = FALSE
Referenced by CT_ifdCmdEepromFile(), and hal_io_recByteT0().