fs.c File Reference
File system.
#include <config.h>
#include <sw.h>
#include <fs.h>
#include <hal.h>
#include <log.h>
#include <string.h>
#include <transaction.h>
#include <types.h>
Functions
bool fs_init (void)
Initialize file system variables.
bool fs_seek (iu16 fid, S_FSTREAM *fs, S_FINFO *fi, iu8 type)
Look for a file in a stream.
bool fs_seekEnd (S_FSTREAM *fs)
Look for the end of files in the stream.
bool fs_getData (S_FPATH *fp, S_FSTREAM *fs, S_FINFO *fi)
Get stream and info for a file specified as a path.
bool fs_getFPath (iu16 fid, S_FPATH *fp, S_FSTREAM *fs, S_FINFO *fi)
Get path, stream and info for a file specified as a FID.
bool fs_delete (iu16 fid)
Delete file specified as fid.
bool fs_create (S_FINFO *fi)
The function creates a file.
Variables
iu16 fsstart
Start address of the MF file header.
iu16 fssize
Size of the content area of the MF.
S_FPATH selected
Path specified of the currently selected file.
Detailed Description
File system.
Id:
fs.c,v 1.23 2002/12/22 15:42:55 m Exp
Function Documentation
bool fs_create (S_FINFO * fi)
The function creates a file.
The functions creates a file with the data in fi. The current file must be a MF or DF. In case the current file is a DF, the file, which should be created, can't be a DF.
Parameters
fi Pointer to S_FINFO, which contains the data of the file to create.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, FALSE, s_finfo::fid, fs_getData(), fs_seek(), fs_seekEnd(), FS_TYPE_DF, FS_TYPE_EF, fssize, fsstart, fstream_write(), s_fstream::pos, s_fstream::size, s_finfo::size, s_fstream::start, SW_FILE_EXISTS, SW_FILE_TO_SHORT, sw_set(), SW_WRONG_DATA, ta_commit(), ta_setdata(), and s_finfo::type.
Referenced by cmd_create(), and main().
bool fs_delete (iu16 fid)
Delete file specified as fid.
The function looks for the fid in the current file, which must be a MF or DF. The file, which should be deleted must be the last one in the current MF or DF.
Parameters
fid ID of the file to delete.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, FALSE, fs_getData(), FS_HEADER_SIZE, fstream_read(), fstream_write(), s_fstream::pos, s_finfo::size, s_fstream::size, s_fstream::start, SW_INCOMPATIBLE_FILE, SW_NOT_ALLOWED, sw_set(), ta_commit(), and ta_setdata().
Referenced by cmd_delete(), and main().
bool fs_getData (S_FPATH * fp, S_FSTREAM * fs, S_FINFO * fi)
Get stream and info for a file specified as a path.
Parameters
fp Pointer to S_FPATH, which is used to supply the information about the file wanted.
fs Pointer to S_FSTREAM, which will be filled with data on success.
fi Pointer to S_FINFO, which will be filled with data on success.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, fs_seek(), FS_TYPE_DF, FS_TYPE_EF, fssize, fsstart, fstream_read(), s_fstream::pos, s_fstream::size, and s_fstream::start.
Referenced by auth_getCheckPinLen(), cmd_create(), cmd_delete(), cmd_readBinary(), cmd_updateBinary(), fs_create(), fs_delete(), fs_getFPath(), and main().
bool fs_getFPath (iu16 fid, S_FPATH * fp, S_FSTREAM * fs, S_FINFO * fi)
Get path, stream and info for a file specified as a FID.
The file is searched for in the order described in the SELECT FILE documentation on the main page.
Parameters
fid File ID to look for.
fp Pointer to S_FPATH, which will be filled with data on success.
fs Pointer to S_FSTREAM, which will be filled with data on success. This can be NULL when no data is wanted.
fi Pointer to S_FINFO, which will be filled with data on success. This can be NULL when no data is wanted.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, fs_getData(), SW_FILE_NOT_FOUND, sw_set(), and SW_WRONG_DATA.
Referenced by cmd_select(), and main().
bool fs_init (void)
Initialize file system variables.
This looks e.g. for the start of the file system and it's size. It must be called after each reset.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References FS_START_PTR_ADDR, fssize, fsstart, and hal_eeprom_read().
Referenced by main().
bool fs_seek (iu16 fid, S_FSTREAM * fs, S_FINFO * fi, iu8 type)
Look for a file in a stream.
Parameters
fid File ID to look for.
fs Pointer to S_FSTREAM, where the FID is searched for. It returns on success a stream on the file found.
fi Pointer to S_FINFO, which will be filled with data on success.
type Type of file wanted.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
Todo There is probably a potential for simplification, when the file type is not handled so rigid.
References fssize, fsstart, fstream_read(), s_fstream::pos, s_fstream::size, s_fstream::start, SW_FILE_NOT_FOUND, and sw_set().
Referenced by fs_create(), and fs_getData().
bool fs_seekEnd (S_FSTREAM * fs)
Look for the end of files in the stream.
Parameters
fs Pointer to S_FSTREAM, which supplies a directory stream and which will be used to return the end position on success.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References fstream_read(), and s_fstream::pos.
Referenced by fs_create().
Variable Documentation
iu16 fssize
Size of the content area of the MF.
Referenced by fs_create(), fs_getData(), fs_init(), fs_seek(), and main().
iu16 fsstart
Start address of the MF file header.
Referenced by fs_create(), fs_getData(), fs_init(), fs_seek(), and main().
S_FPATH selected
Path specified of the currently selected file.
Todo Saving here a S_FINFO and/or S_FSTREAM of the selected file might reduce the code size.
Referenced by cmd_create(), cmd_delete(), cmd_readBinary(), cmd_select(), cmd_updateBinary(), and main().