fs.h File Reference
File system declarations.
#include <types.h>
#include <fstream.h>
Data Structures
struct s_fpath
File path specifier.
struct s_finfo
File info struct. This is directly written as a file header in the file system.
Defines
#define FS_TYPE_DF 0x38
File type DF.
#define FS_TYPE_EF 0x00
File type EF.
#define FS_HEADER_SIZE sizeof(S_FINFO)
Size of the file header, which is the same as S_FINFO.
Typedefs
typedef struct s_fpath S_FPATH
File path specifier.
typedef struct s_finfo S_FINFO
File info struct. This is directly written as a file header in the file system.
Functions
bool fs_init (void)
Initialize file system variables.
bool fs_seek (iu16 fid, S_FSTREAM *fs, S_FINFO *fi, iu8 type)
Look for a file in a stream.
bool fs_seekEnd (S_FSTREAM *fs)
Look for the end of files in the stream.
bool fs_getData (S_FPATH *fp, S_FSTREAM *fs, S_FINFO *fi)
Get stream and info for a file specified as a path.
bool fs_getFPath (iu16 fid, S_FPATH *fp, S_FSTREAM *fs, S_FINFO *fi)
Get path, stream and info for a file specified as a FID.
bool fs_delete (iu16 fid)
Delete file specified as fid.
bool fs_create (S_FINFO *fi)
The function creates a file.
Variables
S_FPATH selected
Path specified of the currently selected file.
Detailed Description
File system declarations. SOSSE implements a very simple file system. Each file starts with following header:
2 Byte: Content size
2 Byte: ID
1 Byte: Type
1 Byte: Access conditions
Directly after that the content area is located. If the file is a DF, this content area is directly used to add header/content sequences.
After the content area of a file, a content size of 0 must be writen as an end of data marker. This means the data capacity of a MF or DF is the total content size of it minus 2.
Currently the file system support only one level of DFs, i.e. the maximum depth is MF:DF:EF.
There are probably a lot optimization possibilities in this file system, but I think this is not bad for my first designed and implemented file system.
Todo Here are certainly some optimizations possible to reduce code size.
Id:
fs.h,v 1.13 2002/12/22 15:42:55 m Exp
Define Documentation
#define FS_HEADER_SIZE sizeof(S_FINFO)
Size of the file header, which is the same as S_FINFO.
Referenced by fs_delete().
#define FS_TYPE_DF 0x38
File type DF.
Referenced by cmd_create(), cmd_delete(), fs_create(), and fs_getData().
#define FS_TYPE_EF 0x00
File type EF.
Referenced by auth_getCheckPinLen(), cmd_readBinary(), cmd_updateBinary(), fs_create(), and fs_getData().
Typedef Documentation
typedef struct s_finfo S_FINFO
File info struct. This is directly written as a file header in the file system.
typedef struct s_fpath S_FPATH
File path specifier.
Todo There is probably a potential for simplification, when the file type (DF/EF) is not handled so rigid.
Function Documentation
bool fs_create (S_FINFO * fi)
The function creates a file.
The functions creates a file with the data in fi. The current file must be a MF or DF. In case the current file is a DF, the file, which should be created, can't be a DF.
Parameters
fi Pointer to S_FINFO, which contains the data of the file to create.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, FALSE, s_finfo::fid, fs_getData(), fs_seek(), fs_seekEnd(), FS_TYPE_DF, FS_TYPE_EF, fssize, fsstart, fstream_write(), s_fstream::pos, s_fstream::size, s_finfo::size, s_fstream::start, SW_FILE_EXISTS, SW_FILE_TO_SHORT, sw_set(), SW_WRONG_DATA, ta_commit(), ta_setdata(), and s_finfo::type.
Referenced by cmd_create(), and main().
bool fs_delete (iu16 fid)
Delete file specified as fid.
The function looks for the fid in the current file, which must be a MF or DF. The file, which should be deleted must be the last one in the current MF or DF.
Parameters
fid ID of the file to delete.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, FALSE, fs_getData(), FS_HEADER_SIZE, fstream_read(), fstream_write(), s_fstream::pos, s_finfo::size, s_fstream::size, s_fstream::start, SW_INCOMPATIBLE_FILE, SW_NOT_ALLOWED, sw_set(), ta_commit(), and ta_setdata().
Referenced by cmd_delete(), and main().
bool fs_getData (S_FPATH * fp, S_FSTREAM * fs, S_FINFO * fi)
Get stream and info for a file specified as a path.
Parameters
fp Pointer to S_FPATH, which is used to supply the information about the file wanted.
fs Pointer to S_FSTREAM, which will be filled with data on success.
fi Pointer to S_FINFO, which will be filled with data on success.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, fs_seek(), FS_TYPE_DF, FS_TYPE_EF, fssize, fsstart, fstream_read(), s_fstream::pos, s_fstream::size, and s_fstream::start.
Referenced by auth_getCheckPinLen(), cmd_create(), cmd_delete(), cmd_readBinary(), cmd_updateBinary(), fs_create(), fs_delete(), fs_getFPath(), and main().
bool fs_getFPath (iu16 fid, S_FPATH * fp, S_FSTREAM * fs, S_FINFO * fi)
Get path, stream and info for a file specified as a FID.
The file is searched for in the order described in the SELECT FILE documentation on the main page.
Parameters
fid File ID to look for.
fp Pointer to S_FPATH, which will be filled with data on success.
fs Pointer to S_FSTREAM, which will be filled with data on success. This can be NULL when no data is wanted.
fi Pointer to S_FINFO, which will be filled with data on success. This can be NULL when no data is wanted.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fpath::df, s_fpath::ef, fs_getData(), SW_FILE_NOT_FOUND, sw_set(), and SW_WRONG_DATA.
Referenced by cmd_select(), and main().
bool fs_init (void)
Initialize file system variables.
This looks e.g. for the start of the file system and it's size. It must be called after each reset.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References FS_START_PTR_ADDR, fssize, fsstart, and hal_eeprom_read().
Referenced by main().
bool fs_seek (iu16 fid, S_FSTREAM * fs, S_FINFO * fi, iu8 type)
Look for a file in a stream.
Parameters
fid File ID to look for.
fs Pointer to S_FSTREAM, where the FID is searched for. It returns on success a stream on the file found.
fi Pointer to S_FINFO, which will be filled with data on success.
type Type of file wanted.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
Todo There is probably a potential for simplification, when the file type is not handled so rigid.
References fssize, fsstart, fstream_read(), s_fstream::pos, s_fstream::size, s_fstream::start, SW_FILE_NOT_FOUND, and sw_set().
Referenced by fs_create(), and fs_getData().
bool fs_seekEnd (S_FSTREAM * fs)
Look for the end of files in the stream.
Parameters
fs Pointer to S_FSTREAM, which supplies a directory stream and which will be used to return the end position on success.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References fstream_read(), and s_fstream::pos.
Referenced by fs_create().
Variable Documentation
S_FPATH selected
Path specified of the currently selected file.
Todo Saving here a S_FINFO and/or S_FSTREAM of the selected file might reduce the code size.
Referenced by cmd_create(), cmd_delete(), cmd_readBinary(), cmd_select(), cmd_updateBinary(), and main().