fstest.c File Reference
Test program for file system functions.
#include <stdio.h>
#include <auth.h>
#include <fs.h>
#include <fstream.h>
#include <hal.h>
Functions
int main (int argc, char *argv[])
Variables
iu16 fsstart
Start address of the MF file header.
iu16 fssize
Size of the content area of the MF.
iu8 authstate
Variable indicating current authentication state.
Detailed Description
Test program for file system functions.
Id:
fstest.c,v 1.11 2002/12/22 15:42:55 m Exp
Function Documentation
int main (int argc, char * argv[])
References s_finfo::ac, AUTH_AC_ADM, AUTH_AC_ALW, AUTH_AC_PIN, auth_checkAc(), authstate, s_fpath::df, s_fpath::ef, s_finfo::fid, fs_create(), fs_delete(), fs_getData(), fs_getFPath(), fs_init(), fssize, fsstart, fstream_read(), fstream_write(), hal_eeprom_read(), hal_init(), s_fstream::pos, selected, s_fstream::size, s_finfo::size, s_fstream::start, and s_finfo::type.
Variable Documentation
iu8 authstate
Variable indicating current authentication state.
Single bit flags indicate, which authorization process has been successful. The flag is cleared, at the reset of the card and after unsuccessful authorization processes.
Valid flags are:
AUTH_FLAG_PIN
AUTH_FLAG_KEY
Referenced by auth_checkAc(), auth_createVerifyCryptogram(), auth_init(), auth_verifyPin(), and main().
iu16 fssize
Size of the content area of the MF.
Referenced by fs_create(), fs_getData(), fs_init(), fs_seek(), and main().
iu16 fsstart
Start address of the MF file header.
Referenced by fs_create(), fs_getData(), fs_init(), fs_seek(), and main().