fstream.h File Reference
File stream declarations.
#include <types.h>
Data Structures
struct s_fstream
Stream struct.
Typedefs
typedef struct s_fstream S_FSTREAM
Stream struct.
Functions
bool fstream_read (S_FSTREAM *fs, iu8 *dst, iu8 len)
Read data from a stream.
bool fstream_write (S_FSTREAM *fs, iu8 *src, iu8 len)
Write data to a stream.
bool fstream_test (S_FSTREAM *fs, iu16 len)
This function tests, if enough space is available to read or write len bytes.
Detailed Description
File stream declarations. These streams are used to pass more easily EEPROM areas around and to reduce the chances of overwriting unwanted EEPROM areas, e.g. by overflowing the data area.
This is a very slim version of the streams implemented in cryptlib from Peter Gutmann.
Id:
fstream.h,v 1.8 2002/12/22 15:42:55 m Exp
Typedef Documentation
typedef struct s_fstream S_FSTREAM
Stream struct.
Function Documentation
bool fstream_read (S_FSTREAM * fs, iu8 * dst, iu8 len)
Read data from a stream.
Either this functions reads all data or nothing.
Parameters
fs Pointer to S_FSTREAM, on which it should be operated.
dst Pointer to the data destination.
len Length of the data
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References fstream_test(), hal_eeprom_read(), s_fstream::pos, and s_fstream::start.
Referenced by cmd_readBinary(), fs_delete(), fs_getData(), fs_seek(), fs_seekEnd(), and main().
bool fstream_test (S_FSTREAM * fs, iu16 len)
This function tests, if enough space is available to read or write len bytes.
Parameters
fs Pointer to S_FSTREAM, on which it should be operated.
len Length of the data
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References s_fstream::pos, s_fstream::size, SW_FILE_TO_SHORT, and sw_set().
Referenced by cmd_readBinary(), cmd_updateBinary(), fstream_read(), and fstream_write().
bool fstream_write (S_FSTREAM * fs, iu8 * src, iu8 len)
Write data to a stream.
This functions tries to write all or nothing.
Parameters
fs Pointer to S_FSTREAM, on which it should be operated.
src Pointer to data source.
len Length of the data
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References fstream_test(), hal_eeprom_write(), s_fstream::pos, and s_fstream::start.
Referenced by cmd_updateBinary(), fs_create(), fs_delete(), and main().