hal-emu.c File Reference
HAL emulation for Linux.
#include <config.h>
#include <sio/sio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <crypt.h>
#include <sw.h>
#include <types.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
Defines
#define PORT `/dev/ttyS0`
Functions
void hal_init (void)
Initializes the HAL.
void hal_destroy (void)
bool hal_eeprom_read (iu8 *dst, iu16 src, iu8 len)
Read data from EEPROM.
bool hal_eeprom_write (iu16 dst, iu8 *src, iu8 len)
Write data to EEPROM.
void hal_io_sendByteT0 (iu8 b)
Send a byte with T=0 error detection and recovery.
iu8 hal_io_recByteT0 (void)
Receive a byte with T=0 error detection and recovery.
bool hal_rnd_getBlock (iu8 *dst)
Returns 8 random bytes.
Variables
iu8 eeprom [1 *1024]
int halsend
Detailed Description
HAL emulation for Linux.
Id:
hal-emu.c,v 1.18 2003/03/30 12:42:21 m Exp
Define Documentation
#define PORT `/dev/ttyS0`
Referenced by hal_init().
Function Documentation
void hal_destroy (void)
bool hal_eeprom_read (iu8 * dst, iu16 src, iu8 len)
Read data from EEPROM.
The internal EEPROM begins at address 0, the external EEPROM is located subsequently.
Parameters
dst Pointer to destination area.
src EEPROM source address.
len Length of data in bytes.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
Referenced by auth_createVerifyCryptogram(), auth_verifyPin(), cmd_read(), fs_init(), fstream_read(), hal_rnd_getBlock(), main(), and ta_commit().
bool hal_eeprom_write (iu16 dst, iu8 * src, iu8 len)
Write data to EEPROM.
The internal EEPROM begins at address 0, the external EEPROM is located subsequently.
Parameters
dst EEPROM destination address
src Pointer to source area.
len Length of data in bytes.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
Referenced by auth_createVerifyCryptogram(), auth_setPin(), auth_verifyPin(), cmd_write(), fstream_write(), hal_rnd_getBlock(), log_add(), log_init(), ta_commit(), and ta_setdata().
void hal_init (void)
Initializes the HAL.
Must be called after each reset.
Referenced by main().
iu8 hal_io_recByteT0 (void)
Receive a byte with T=0 error detection and recovery.
Currently only 9600 bps at 3.58MHz with direct convention is supported.
Returns
This function returns a received byte. There can't be an error, because T=0 tries endlessly to receive a characters. (And if there is really an error, what should SOSSE do with it anyway?)
Referenced by cmd_delete(), cmd_select(), cmd_updateBinary(), cmd_write(), main(), and t0_recBlock().
void hal_io_sendByteT0 (iu8 b)
Send a byte with T=0 error detection and recovery.
Currently only 9600 bps at 3.58MHz with direct convention is supported.
Parameters
b Byte to send.
Referenced by cmd_getChallenge(), cmd_getResponse(), cmd_read(), cmd_readBinary(), main(), t0_sendAck(), t0_sendCAck(), t0_sendSw(), and t0_sendWord().
bool hal_rnd_getBlock (iu8 * dst)
Returns 8 random bytes.
The current AVR implementation does not produce real random numbers, but pseudo random numbers. These are produced by a X9.17 generator modified to use a counter instead of a timer. The state of this PRNG is held at RAND_STATE_ADDR. The start value (at least the key) at this address should be unique for every card.
Parameters
dst Pointer to the destination, where the 8 random bytes should be written.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
Note
There is still a simpler PRNG in the code, which uses 16 bytes RAM and 126 bytes ROM less than the X9.17 generator.
Referenced by auth_getChallenge(), and main().
Variable Documentation
iu8 eeprom[1 *1024]
Referenced by hal_eeprom_read(), hal_eeprom_write(), hal_init(), and hal_io_recByteT0().
int halsend
Referenced by hal_init(), hal_io_recByteT0(), and hal_io_sendByteT0().