log.c File Reference
Logging functions.
#include <config.h>
#include <hal.h>
#include <log.h>
#include <types.h>
Functions
void log_init (void)
void log_add (iu8 tag, iu8 *data, iu8 len)
Variables
iu16 dst = LOG_START+2
bool log_enable
Enables/disables logging.
Detailed Description
Logging functions.
Id:
log.c,v 1.6 2002/12/22 15:42:55 m Exp
Function Documentation
void log_add (iu8 tag, iu8 * data, iu8 len)
References dst, hal_eeprom_write(), log_enable, and LOG_START.
void log_init (void)
References dst, hal_eeprom_write(), log_enable, and LOG_START.
Referenced by main().
Variable Documentation
iu16 dst = LOG_START+2
Referenced by log_add(), and log_init().
bool log_enable
Enables/disables logging.
This must be set the TRUE, before any log_add has an effect. It can be also changed in between to switch off and on logging to reduce unwanted data in the logging area.
Referenced by log_add(), and log_init().