sw.h File Reference
Errno declarations.
#include <types.h>
Enumerations
enum SW {
SW_ACCESS_DENIED = 0x6982,
SW_AUTH_BLOCKED = 0x6983,
SW_AVAILABLE = 0x6100,
SW_CHANGE_MEMORY_ERROR = 0x6581,
SW_COUNTER = 0x63C0,
SW_EOD = 0x6282,
SW_FILE_EXISTS = 0x6A89,
SW_FILE_FILLED = 0x6381,
SW_FILE_NOT_FOUND = 0x6A82,
SW_FILE_TO_SHORT = 0x6A84,
SW_INCOMPATIBLE_FILE = 0x6981,
SW_LC_INCONSISTEND_WITH_P1P2 = 0x6A87,
SW_NOT_ALLOWED = 0x6986,
SW_NOT_SUPPORTED = 0x6A81,
SW_OK = 0x9000,
SW_OTHER = 0x6F00,
SW_REF_DATA_INVALID = 0x6984,
SW_REF_DATA_NOT_FOUND = 0x6A88,
SW_VERIFCATION_FAILED = 0x6300,
SW_WRONG_CLA = 0x6E00,
SW_WRONG_CONDITION = 0x6985,
SW_WRONG_DATA = 0x6A80,
SW_WRONG_INS = 0x6D00,
SW_WRONG_LE = 0x6C00,
SW_WRONG_LEN = 0x6700,
SW_WRONG_P1P2 = 0x6A86,
SW_WRONG_REFERENCE = 0x6B00
 }
Status word values.
Functions
void sw_set (iu16 value)
Function for setting sw.
Variables
iu16 sw
Status word returned by functions.
Detailed Description
Errno declarations. See also for the man page of sw.
Id:
sw.h,v 1.1 2002/12/22 15:42:55 m Exp
Enumeration Type Documentation
enum SW
Status word values.
Note
Implement this as defines, because doxygen apparently can't handle this?
Enumerator:
SW_ACCESS_DENIED
SW_AUTH_BLOCKED
SW_AVAILABLE
SW_CHANGE_MEMORY_ERROR
SW_COUNTER
SW_EOD
SW_FILE_EXISTS
SW_FILE_FILLED
SW_FILE_NOT_FOUND
SW_FILE_TO_SHORT
SW_INCOMPATIBLE_FILE
SW_LC_INCONSISTEND_WITH_P1P2
SW_NOT_ALLOWED
SW_NOT_SUPPORTED
SW_OK
SW_OTHER
SW_REF_DATA_INVALID
SW_REF_DATA_NOT_FOUND
SW_VERIFCATION_FAILED
SW_WRONG_CLA
SW_WRONG_CONDITION
SW_WRONG_DATA
SW_WRONG_INS
SW_WRONG_LE
SW_WRONG_LEN
SW_WRONG_P1P2
SW_WRONG_REFERENCE
Function Documentation
void sw_set (iu16 value)
Function for setting sw.
This function reduces the code size on the AVR architecture.
Referenced by auth_checkAc(), auth_createVerifyCryptogram(), auth_getChallenge(), auth_getCheckPinLen(), auth_verifyPin(), cmd_changeUnblockPIN(), cmd_create(), cmd_delete(), cmd_extAuth(), cmd_getChallenge(), cmd_getResponse(), cmd_intAuth(), cmd_read(), cmd_readBinary(), cmd_select(), cmd_updateBinary(), cmd_verifyKeyPIN(), cmd_write(), fs_create(), fs_delete(), fs_getFPath(), fs_seek(), fstream_test(), hal_eeprom_read(), hal_eeprom_write(), t0_testP1P2(), t0_testP3(), ta_commit(), and ta_setdata().
Variable Documentation
iu16 sw
Status word returned by functions.
The state of sw is undefined, on return value TRUE.
The content of this variable is returned at the end of the command interpreter loop. Functions falled from the command interpreter loop should set it to SW_OK if they return without error.
Referenced by auth_getCheckPinLen(), main(), and t0_sendSw().