sw.c File Reference
Errno functions.
#include <config.h>
#include <sw.h>
#include <types.h>
Functions
void sw_set (iu16 value)
Function for setting sw.
Variables
iu16 sw
Status word returned by functions.
Detailed Description
Errno functions.
Id:
sw.c,v 1.1 2002/12/22 15:42:55 m Exp
Function Documentation
void sw_set (iu16 value)
Function for setting sw.
This function reduces the code size on the AVR architecture.
Referenced by auth_checkAc(), auth_createVerifyCryptogram(), auth_getChallenge(), auth_getCheckPinLen(), auth_verifyPin(), cmd_changeUnblockPIN(), cmd_create(), cmd_delete(), cmd_extAuth(), cmd_getChallenge(), cmd_getResponse(), cmd_intAuth(), cmd_read(), cmd_readBinary(), cmd_select(), cmd_updateBinary(), cmd_verifyKeyPIN(), cmd_write(), fs_create(), fs_delete(), fs_getFPath(), fs_seek(), fstream_test(), hal_eeprom_read(), hal_eeprom_write(), t0_testP1P2(), t0_testP3(), ta_commit(), and ta_setdata().
Variable Documentation
iu16 sw
Status word returned by functions.
The state of sw is undefined, on return value TRUE.
The content of this variable is returned at the end of the command interpreter loop. Functions falled from the command interpreter loop should set it to SW_OK if they return without error.
Referenced by auth_getCheckPinLen(), main(), and t0_sendSw().