t0.h File Reference
T=0 declarations.
Functions
void t0_sendAck (void)
Send ACK byte.
void t0_sendCAck (void)
Send complemented ACK byte.
void t0_sendSw (void)
Send word in sw.
void t0_sendWord (iu16 w)
Send word.
void t0_recBlock (iu8 *dst, iu8 len)
Receive mutiple bytes.
bool t0_testP1P2 (iu16 p1p2)
Test P1P2 for correct content.
bool t0_testP3 (iu8 p3)
Test P3 for correct content.
Variables
iu8 header [5]
Header of the current command.
Detailed Description
T=0 declarations. T=0 is not implemented fully as library, but must be partly done in the commands itself. This reduces the RAM requirements. E.g. when doing an Update Binary the data must not be received in total before writing, but can be received and written in single bytes.
Id:
t0.h,v 1.12 2002/12/22 15:42:55 m Exp
Function Documentation
void t0_recBlock (iu8 * dst, iu8 len)
Receive mutiple bytes.
Receive len bytes and write them to dst.
Parameters
dst Pointer to destination area in RAM.
len Data bytes to receive.
References hal_io_recByteT0().
Referenced by cmd_changeUnblockPIN(), cmd_create(), cmd_extAuth(), cmd_intAuth(), and cmd_verifyKeyPIN().
void t0_sendAck (void)
Send ACK byte.
Sends the for the current command correct ACK byte to the terminal.
References hal_io_sendByteT0(), and header.
Referenced by cmd_changeUnblockPIN(), cmd_create(), cmd_delete(), cmd_extAuth(), cmd_getChallenge(), cmd_getResponse(), cmd_intAuth(), cmd_read(), cmd_readBinary(), cmd_select(), and cmd_verifyKeyPIN().
void t0_sendCAck (void)
Send complemented ACK byte.
Sends the for the current command correct complemented ACK byte to the terminal.
References hal_io_sendByteT0(), and header.
Referenced by cmd_updateBinary(), and cmd_write().
void t0_sendSw (void)
Send word in sw.
Sends the word in sw the the terminal. This is used to return the status word at the end of the command interpreter loop in main().
References hal_io_sendByteT0(), and sw.
Referenced by main().
void t0_sendWord (iu16 w)
Send word.
Parameters
w Word to send.
References hal_io_sendByteT0().
Referenced by main().
bool t0_testP1P2 (iu16 p1p2)
Test P1P2 for correct content.
Compares the values of P1 and P2 in header to p1p2. If they differ, sw is set to SW_WRONG_P1P2 and FALSE is returned.
Parameters
p1p2 Target value of P1P2.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References header, sw_set(), and SW_WRONG_P1P2.
Referenced by cmd_changeUnblockPIN(), cmd_create(), cmd_delete(), cmd_extAuth(), cmd_getChallenge(), cmd_getResponse(), cmd_intAuth(), cmd_select(), and cmd_verifyKeyPIN().
bool t0_testP3 (iu8 p3)
Test P3 for correct content.
Compares the value of P3 in header to p3. If they differ, sw is set to SW_WRONG_P1P2 and FALSE is returned.
Parameters
p3 Target value of P3.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References header, sw_set(), and SW_WRONG_LEN.
Referenced by cmd_changeUnblockPIN(), cmd_create(), cmd_delete(), cmd_extAuth(), cmd_getChallenge(), cmd_getResponse(), cmd_intAuth(), cmd_select(), cmd_updateBinary(), cmd_verifyKeyPIN(), and cmd_write().
Variable Documentation
iu8 header[5]
Header of the current command.
This global variable contains the header (CLA INS P1 P2 P3) of the current command. It is fetched in the command interpreter loop in main().
Referenced by cmd_read(), cmd_write(), main(), t0_sendAck(), t0_sendCAck(), t0_testP1P2(), and t0_testP3().