tea.c File Reference
TEA functions.
#include <config.h>
#include <tea.h>
#include <tools.h>
Defines
#define TEA_SMALL
#define hton_ul(x, y)
Functions
iu32 tea_func (iu32 *in, iu32 *sum, iu32 *k)
void tea_enc (iu32 *v, iu32 *k)
TEA encryption function.
void tea_dec (iu32 *v, iu32 *k)
TEA decryption function.
Detailed Description
TEA functions.
Id:
tea.c,v 1.6 2003/04/02 23:57:54 m Exp
Define Documentation
#define hton_ul(x, y)
Referenced by tea_dec(), and tea_enc().
#define TEA_SMALL
Function Documentation
void tea_dec (iu32 * v, iu32 * k)
TEA decryption function.
This function decrypts v with k and returns the decrypted data in v.
Parameters
v Array of two long values containing the data block.
k Array of four long values containing the key.
References DELTA, hton_ul, and tea_func().
void tea_enc (iu32 * v, iu32 * k)
TEA encryption function.
This function encrypts v with k and returns the encrypted data in v.
Parameters
v Array of two long values containing the data block.
k Array of four long values containing the key.
References hton_ul, and tea_func().
iu32 tea_func (iu32 * in, iu32 * sum, iu32 * k)
Referenced by tea_dec(), and tea_enc().