transaction.c File Reference
Transaction functions.
#include <config.h>
#include <sw.h>
#include <hal.h>
#include <transaction.h>
#include <types.h>
Functions
bool ta_setdata (iu8 *data, iu8 len, iu16 dst)
Begins a transaction and sets the data.
bool ta_commit (void)
Commits the data in the transaction buffer.
Detailed Description
Transaction functions.
Id:
transaction.c,v 1.11 2002/12/22 15:42:56 m Exp
Function Documentation
bool ta_commit (void)
Commits the data in the transaction buffer.
Data is written to the destination specified in ta_setdata(). The state is then set to clean.
This function must be called after each reset to commit pending transactions.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References hal_eeprom_read(), hal_eeprom_write(), SW_OTHER, sw_set(), TRANSAC_DATA_ADDR, TRANSAC_DATA_LEN, TRANSAC_STATE_ADDR, TRANSAC_STATE_CLEAN, and TRANSAC_STATE_DATA.
Referenced by auth_createVerifyCryptogram(), auth_setPin(), auth_verifyPin(), fs_create(), fs_delete(), and main().
bool ta_setdata (iu8 * data, iu8 len, iu16 dst)
Begins a transaction and sets the data.
data/len bytes are written to the transaction buffer. The destination address is also stored there. Then the state is set to TRANSAC_STATE_DATA.
Parameters
data Pointer to the data to write into the transaction buffer.
len Length of the data. (Max.: TRANSAC_DATA_LEN)
dst Destination of the data in EEPROM.
Return values
TRUE on success.
FALSE on failure. Error code given in sw.
References hal_eeprom_write(), SW_FILE_TO_SHORT, sw_set(), TRANSAC_DATA_ADDR, TRANSAC_DATA_LEN, and TRANSAC_STATE_ADDR.
Referenced by auth_createVerifyCryptogram(), auth_setPin(), auth_verifyPin(), fs_create(), and fs_delete().